Update sorter.yml

diff --git a/.github/workflows/sorter.yml b/.github/workflows/sorter.yml
--- a/.github/workflows/sorter.yml
+++ b/.github/workflows/sorter.yml
@@ -54,13 +54,13 @@ jobs:
         git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
       
 # Could always disable this section to apply bug fixes
-#    - name: Stop if no changes
-#      run: |
-#        if [[ "${{ steps.changesin.outputs.changed }}" != "true" ]]; then
-#          echo "No changes in input file, exiting"
-#          echo "::error::No changes in input file, stopping workflow"
-#          exit 1
-#        fi
+    - name: Stop if no changes
+      run: |
+        if [[ "${{ steps.changesin.outputs.changed }}" != "true" ]]; then
+          echo "No changes in input file, exiting"
+          echo "::error::No changes in input file, stopping workflow"
+          exit 1
+        fi
     
     - name: Commit and push if there are changes
       if: steps.changesin.outputs.changed == 'true' 
